spring:
    application:
        name: iot-vmp-vmanager
        # 影子数据存储方式，支持redis、jdbc
        database: redis
        # 通信方式，支持kafka、http
        communicate: http
    redis:
        host: 127.0.0.1
        port: 6379
        password: root
        timeout: 10000
    datasource: 
        name: sip
        url: jdbc:mysql://127.0.0.1:3306/eiot?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
server:
    port: 8080
sip:
#   ip: 10.200.64.63
    ip: 192.168.0.102
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    domain: 3701020049
    id: 37010200492000000001
    # 默认设备认证密码，后续扩展使用设备单独密码
    password: admin123
media:
#   ip: 10.200.64.88
    ip: 192.168.0.102
    port: 10000